### ISSUE TITLE
Get spell information

### ISSUE THREAD

**Issue by sxe** [laytya/LazyScript#15]
I hope it's ok to ask this question here, since it's not directly related to LazyScript but still somewhat relevant. 

I play on a custom server which added a bunch of new abilities, debuffs and forms I want to add to LazyScript.

I checked to code and adding those seems pretty straight forward but I can't figure out how to get the information about a specific new spell for example. 

I found https://vanilla-wow-archive.fandom.com/wiki/API_GetSpellInfo but no matter what spell name or spell id I try it always throws an error: `attempt to call global GetSpellInfo a nil value` .

Since you are an experienced addon developer I would really appreciate some clarification or a link to some kind of documentation that could help me.

Cheers

**Comment by sxe** [comment]
Hey @shikulja thanks for the suggestion. 
Do I have to extract it from one of the resource files first? Cause I don't have a Spell.dbc file.
 Besides that, I need the spell icon name (e.g.: Spell_Holy_FlashHeal ) in particular, since that seems to be the crucial part in how LazyScript seems to recognize the actual spell.

**Comment by shikulja** [comment]
if there is dbc.MPQ, extract it from it, or look in other game archives
<img width="622" alt="image" src="https://github.com/laytya/LazyScript/assets/3386359/e5edee1e-3f8f-49ec-8a46-4b66d93bc1a6">

SpellIcon.dbc is also available, both tables need to be matched by ID
<img width="760" alt="image" src="https://github.com/laytya/LazyScript/assets/3386359/250cc850-cca7-453d-a4cb-cbce244b0c9a">
<img width="330" alt="image" src="https://github.com/laytya/LazyScript/assets/3386359/91bd1737-1359-478a-8b44-539823d091ec">

**Comment by sxe** [comment]
Hey buddy, appreciate your replay. I was able to open Spell. dbc and SpellIcon.dbc as well, so that worked! 
Sadly I can't find the info I need in there. I was ablte to see that the icon name apparently is Spell_Holy_HolySmite but that doesn't work either cause it's already used by a different spell. I have no idea.

Anyways, thanks. I will dig a bit more if I find the time.

**Comment by sxe** [comment]
That's good to know, unfortunately when I use that icon in LazyScript it just won't work. It keeps telling me to put the spell on the hotbar. Probably cause it's still not the correct icon cause that icon is already in LazyScript for an other spell.
