### ISSUE TITLE
support for more recent clients

### ISSUE THREAD

**Issue by github12wykrzyk** [laytya/LazyScript#17]
thank you for this absolutely FANTASTIC addon. theres been many times ive had more fun writing lazyscript macros than playing the game itself. the things you can do with it are absolutely out of this world and easily the most fun ive had playing this game in 20 years.

is there any way to make this addon work on tbc/wotlk based clients? with lua unlockers/hacks? or any other way

**Comment by laytya** [comment]
its impossible

**Comment by github12wykrzyk** [comment]
can you tell me why?

**Comment by HugeMcBigger** [comment]
> can you tell me why?

The TBC prepatch changed how lua scripts work. One thing it did was break lazyscript
