### ISSUE TITLE
Совместимость с фреймами pfUI 

### ISSUE THREAD

**Issue by gamer4eg** [laytya/LazyScript#2]
Сабж https://github.com/shagu/pfUI/issues/504

**Comment by laytya** [comment]
а с другими фреймами работает? 
и покажи скрипт чтоб потестить

**Comment by laytya** [comment]
Added compatibility fo mouseover on LUNA, pfUI, NotGrid

**Comment by laytya** [comment]
in https://github.com/laytya/LazyScript/commit/3456d1c3d84d978319a821f48b2079673fb31358
