### ISSUE TITLE
Suggestions for enhancement LazyScript

### ISSUE THREAD

**Issue by 0ldi** [laytya/LazyScript#3]
Class check criteria is very necessary, something like:
-if[Not]PartyHaveClass={Druid,Hunter,Mage,Paladin,Priest,Rogue,Shaman,Warlock,Warrior}
-if[Not]RaidHaveClass={Druid,Hunter,Mage,Paladin,Priest,Rogue,Shaman,Warlock,Warrior}

This was very useful for situations where you need an announcement of missing of totems, buffs. But if the buffer is not present, then there is no nasty spam.

It's must be something like `for i=1,4 do if UnitClass("party"..i) == "class"`  but adding new criteria in LazyScript too hard for me

**Comment by 0ldi** [comment]
I make this:

> function lazyScript.masks.PartyHaveClass(class)
> 	return function()
> 		for i=1,4 do
> 			return (class == UnitClass("party"..i))
> 		end	
> 	end
> end
> 
> function lazyScript.bitParsers.ifPartyHaveClass(bit, actions, masks)
>    if (not lazyScript.rebit(bit, "^if(Not)?PartyHaveClass=?(.+)$")) then
>       return false
>    end
>    local negate = lazyScript.negate1()
>    local subMasks = {}
>    for class in string.gfind(lazyScript.match2, "[^,]+") do
>       table.insert(subMasks, lazyScript.masks.PartyHaveClass(class))
>    end
>    table.insert(masks, lazyScript.orWrapper(subMasks, negate))
>    return true
> end

but it's not work. Checks only partymember#1, I cant make all party cheking

**Comment by laytya** [comment]
Не верная логика проверки - но это можно запилить

**Comment by laytya** [comment]
Added in [commit](https://github.com/laytya/LazyScript/commit/dcbaf62e40437a31130065c8abd8a432b3ad3827)
