### ISSUE TITLE
Execute Doesnt work

### ISSUE THREAD

**Issue by ghost** [laytya/LazyScript#5]
Hello i downloaded lazyscript from here and the fallowing line of my code 
execute-ifTarget<20%hp
is not working, checks alright  but in action doesnt perform.
I hope u can tellme whats wrong.
also i created this one
hamstring-ifBuffDuration<2s=hamstring
and he doesnt check if the buff is lower than 2sec just casts at any duration.
I was testing on retrowow.
Ty

**Comment by HugeMcBigger** [comment]
You shouldn’t need the if criteria for execute. Lazyscript should skip it if it isn’t castable anyway

As for hamstring, you’re checking for a hamstring buff on yourself. That doesn’t work lol.

try this
hamstring-ifNotTargetHasDebuff=hamstring
hamstring-ifLastUsed>10s=hamstring
