### ISSUE TITLE
Localization overrides global names for keybindings

### ISSUE THREAD

**Issue by AMGarkin** [laytya/LazyScript#6]
Localization.lua contains lots of global variables and some of them are overriding default client variables.
As an example is global variable KEY_2 which is used [GetBindingText("2", "KEY_")](http://wowwiki.wikia.com/wiki/API_GetBindingText) function (action bar shows as binding "Match found: Key: " instead of "2".
I suggest put all the variables into single global array or use AceLocale library.

In order to fix this issue I had to use [original version](https://wow.curseforge.com/projects/project-2907).

**Comment by laytya** [comment]
I can fix KEY_2 in 2 files... but converting to ace or something else - its alot of work.
